### ISSUE TITLE
no version shown upon `--version`

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#175]

**Comment by rekado** [comment]
I cannot reproduce this:

```sh
./pigx-chipseq --version
PiGx ChIPseq Pipeline.
Version: 0.0.53

Copyright © 2017-2022 Vedran Franke, Alexander Gosdschan, Ricardo Wurmus.
$ [env] 
```

**Comment by alexg9010** [comment]
sorry, I was not very specific. 

this happens with the version installed via guix.

**Comment by rekado** [comment]
Ah, that's probably because the `VERSION` file is not part of the tarball created with `make distcheck`.

**Comment by rekado** [comment]
I see that pigx-rnaseq has the same problem.  We're using the `@PACKAGE_VERSION@` placeholder in META.in.  We have a value for `PACKAGE_VERSION` in the configure script, so it should end up in `META` after the `configure` script has been completed.

The problem appears, because in Guix we're re-bootstrapping the build system (after having applied a patch to remove pandoc-citeproc).  This happens in an environment where `VERSION` does not exist, because `VERSION` is not part of the tarball.

We should probably just include VERSION in the tarball.

**Comment by rekado** [comment]
Done in pigx-rnaseq: 90761aba01bca4d44b5f88573b9b52fda4ca8486  Seems to work fine.
