### ISSUE TITLE
Do we need to keep the scorematrices ? 

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_chipseq#67]
The step `knit report` requires a way too large amount of memory, because the RDS created at `Extract_Signal_Annotation` (https://github.com/BIMSBbioinfo/pigx_chipseq/blob/master/scripts/Extract_Signal_Annotation.R#L63) keeps the 11 scorematrixlist objects for every genomic annotation with a scorematrix for every sample in `lsml` list, even though the profile signal is already summarized in `profiles` tibble. 
The same `lsml` lists is passed to `Summarize_Data_For_Report`, which leads to the large memory footprint. 

In my example analysis I have 16 samples and the `lstats$Extract_Signal_Annotation$lsml` alone is 28G, without actually beeing used.

**Comment by al2na** [comment]
Can we store stuff in HDF or some on disk stuff ? Maybe that's to do for
genomation as well

**Comment by frenkiboy** [comment]
The score matrices are not needed - I included them because they are always nice to have for downstream analysis, and there was a plan to have a multi heat matrix in the report - but this does not scale with the number of experiments. It seems it's faster calculate them when needed than to have them prepared, especially for a large number of samples.
I think you can comfortably set the sml object to NULL, and everything should go much faster.

**Comment by al2na** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/N5ablA9e/8-test)
